### ISSUE TITLE
Switching from English to Arabic numerals

### ISSUE THREAD

**Issue by MudarAljundi** [hamed/trust#2]
Function to switch any English numeral to Arabic. Copy line 8 to 35:  
https://github.com/MudarAljundi/trust/blob/gh-pages/js/lib/helpers.js
Use the function like the following:  
`var englishNumber = getArabicNumbers(englishNumber);`

Arabic graphics. 
https://github.com/MudarAljundi/trust/blob/gh-pages/social/thumbnail.png (SUPER IMPORTANT)
https://github.com/MudarAljundi/trust/blob/gh-pages/assets/conclusion/summary.png
https://github.com/MudarAljundi/trust/blob/gh-pages/assets/iterated/iterated_payoffs.png

Be aware that iterated_payoffs.png has a small jitter when it switches between the graphics ingame. I'm hoping that it's not very noticeable.

My 80% finished repo is here https://github.com/MudarAljundi/trust

**Comment by MudarAljundi** [comment]
I made a change to the `getArabicNumbers ` function to write the minus sign on the left of the number. Please copy it again now if you have already.

**Comment by hamed** [comment]
This is a good way to format number into Arabic: toLocaleString('fa')
