### ISSUE TITLE
Making this repo standalone?

### ISSUE THREAD

**Issue by farooqkz** [hamed/trust#5]
Hi, How about making this repo standalone?

**Comment by hamed** [comment]
Standalone?

**Comment by farooqkz** [comment]
"Not a fork"
You should send a request via email.

**Comment by hamed** [comment]
What would be the advantage?

**Comment by farooqkz** [comment]
Not much.but you don't pay much for it, too.

**Comment by hamed** [comment]
Then I prefer to be just a fork, so one can know where is this from and what is my contribution.

**Comment by farooqkz** [comment]
read about forks.
